/**
 * PartsSource Design System â Style Dictionary Config (v3 compatible)
 *
 * Transforms Token Studio JSON into:
 *   1. CSS custom properties  â src/tokens/tokens.css
 *   2. Tailwind theme config  â src/tokens/tailwind-tokens.js
 *   3. TypeScript token map   â src/tokens/tokens.ts
 *
 * Run: npx style-dictionary build --config style-dictionary.config.js
 *
 * NOTE: Requires style-dictionary ^3.x (shadow/css was added in v4)
 */

const StyleDictionary = require('style-dictionary');

// âââ Custom transforms ââââââââââââââââââââââââââââââââââââââââââââââââââââââââ

// px â rem for spacing/sizing/radius/border
StyleDictionary.registerTransform({
  name: 'ps/px-to-rem',
  type: 'value',
  matcher: (token) =>
    ['sizing', 'spacing', 'borderRadius', 'borderWidth'].includes(token.type) &&
    typeof token.value === 'string' &&
    token.value.endsWith('px'),
  transformer: (token) => `${parseFloat(token.value) / 16}rem`,
});

// Font size px â rem
StyleDictionary.registerTransform({
  name: 'ps/font-size-rem',
  type: 'value',
  matcher: (token) =>
    token.type === 'fontSizes' &&
    typeof token.value === 'string' &&
    token.value.endsWith('px'),
  transformer: (token) => `${parseFloat(token.value) / 16}rem`,
});

// Opacity decimal â percentage string
StyleDictionary.registerTransform({
  name: 'ps/opacity-percent',
  type: 'value',
  matcher: (token) => token.type === 'opacity',
  transformer: (token) => `${parseFloat(token.value) * 100}%`,
});

// Shadow: flatten Token Studio boxShadow objects â CSS box-shadow string
// (replaces shadow/css which only exists in Style Dictionary v4)
StyleDictionary.registerTransform({
  name: 'ps/shadow-css',
  type: 'value',
  matcher: (token) => token.type === 'boxShadow',
  transformer: (token) => {
    const v = token.value;
    if (typeof v === 'string') return v; // already a string
    if (Array.isArray(v)) {
      // Multiple shadows
      return v.map(s =>
        `${s.x || 0}px ${s.y || 0}px ${s.blur || 0}px ${s.spread || 0}px ${s.color || '#000'}`
      ).join(', ');
    }
    if (typeof v === 'object') {
      return `${v.x || 0}px ${v.y || 0}px ${v.blur || 0}px ${v.spread || 0}px ${v.color || '#000'}`;
    }
    return v;
  },
});

// âââ Transform groups âââââââââââââââââââââââââââââââââââââââââââââââââââââââââ

StyleDictionary.registerTransformGroup({
  name: 'ps/css',
  transforms: [
    'attribute/cti',
    'name/cti/kebab',
    'ps/px-to-rem',
    'ps/font-size-rem',
    'ps/shadow-css',    // custom (replaces shadow/css which is v4-only)
    'color/css',
  ],
});

StyleDictionary.registerTransformGroup({
  name: 'ps/tailwind',
  transforms: [
    'attribute/cti',
    'name/cti/camel',
    'ps/px-to-rem',
    'ps/font-size-rem',
    'color/css',
  ],
});

StyleDictionary.registerTransformGroup({
  name: 'ps/typescript',
  transforms: [
    'attribute/cti',
    'name/cti/camel',
    'color/css',
  ],
});

// âââ Formatters âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ

// Tailwind theme extension object
StyleDictionary.registerFormat({
  name: 'ps/tailwind-theme',
  formatter: ({ dictionary }) => {
    const colors = {};
    const spacing = {};
    const fontSize = {};
    const fontWeight = {};
    const fontFamily = {};
    const borderRadius = {};
    const borderWidth = {};
    const boxShadow = {};
    const opacity = {};

    dictionary.allTokens.forEach((token) => {
      const path  = token.path;
      const value = token.value;

      if (token.type === 'color') {
        const [level, , ...rest] = path;
        if (['semantic', 'primitive'].includes(level)) {
          colors[rest.join('-')] = value;
        }
      } else if (['spacing', 'sizing'].includes(token.type)) {
        spacing[path.slice(-1)[0]] = value;
      } else if (token.type === 'fontSizes') {
        fontSize[path.slice(-1)[0]] = value;
      } else if (token.type === 'fontWeights') {
        fontWeight[path.slice(-1)[0]] = value;
      } else if (token.type === 'fontFamilies') {
        fontFamily[path.slice(-1)[0]] = [value];
      } else if (token.type === 'borderRadius') {
        borderRadius[path.slice(-1)[0]] = value;
      } else if (token.type === 'borderWidth') {
        borderWidth[path.slice(-1)[0]] = value;
      } else if (token.type === 'boxShadow') {
        boxShadow[path.slice(-1)[0]] = value;
      } else if (token.type === 'opacity') {
        opacity[path.slice(-1)[0]] = value;
      }
    });

    return `/** Auto-generated by Style Dictionary â DO NOT EDIT */
const tokens = ${JSON.stringify({ colors, spacing, fontSize, fontWeight, fontFamily, borderRadius, borderWidth, boxShadow, opacity }, null, 2)};

module.exports = {
  theme: {
    extend: tokens,
  },
};
`;
  },
});

// TypeScript token map
StyleDictionary.registerFormat({
  name: 'ps/typescript-tokens',
  formatter: ({ dictionary }) => {
    const tokens = {};
    dictionary.allTokens.forEach((token) => {
      tokens[token.path.join('.')] = token.value;
    });
    return `/** Auto-generated by Style Dictionary â DO NOT EDIT */
export const tokens = ${JSON.stringify(tokens, null, 2)} as const;

export type TokenPath  = keyof typeof tokens;
export type TokenValue = typeof tokens[TokenPath];
`;
  },
});

// âââ Sources ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ

const SOURCE_GLOB = [
  'tokens/tokens.json',
];

// âââ Build config âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ

module.exports = {
  source: SOURCE_GLOB,
  platforms: {

    css: {
      transformGroup: 'ps/css',
      prefix: 'ps',
      buildPath: 'src/tokens/',
      files: [{
        destination: 'tokens.css',
        format: 'css/variables',
        options: { outputReferences: true, selector: ':root' },
        filter: (token) => ['primitive', 'semantic'].includes(token.path[0]),
      }],
    },

    tailwind: {
      transformGroup: 'ps/tailwind',
      buildPath: 'src/tokens/',
      files: [{
        destination: 'tailwind-tokens.js',
        format: 'ps/tailwind-theme',
        filter: (token) => ['primitive', 'semantic'].includes(token.path[0]),
      }],
    },

    typescript: {
      transformGroup: 'ps/typescript',
      buildPath: 'src/tokens/',
      files: [{
        destination: 'tokens.ts',
        format: 'ps/typescript-tokens',
      }],
    },
  },
};
