/** Auto-generated by Style Dictionary — DO NOT EDIT */
export const tokens = {
  "card.aiData": {
    "$value": {
      "$value": {
        "$value": "#002f48",
        "$type": "color",
        "$description": "Midnight — deep headings, secondary brand"
      },
      "$type": "color",
      "$description": "Page headings"
    },
    "$type": "color"
  },
  "card.status": {
    "$value": {
      "$value": {
        "$value": "#002f48",
        "$type": "color",
        "$description": "Midnight — deep headings, secondary brand"
      },
      "$type": "color",
      "$description": "Page headings"
    },
    "$type": "color"
  },
  "card.data": {
    "$value": {
      "$value": {
        "$value": "#002f48",
        "$type": "color",
        "$description": "Midnight — deep headings, secondary brand"
      },
      "$type": "color",
      "$description": "Page headings"
    },
    "$type": "color"
  },
  "dataVisualization.typography": {
    "fontSize": {
      "$value": {
        "$value": "12px",
        "$type": "fontSizes",
        "$description": "Caption / label text"
      },
      "$type": "fontSizes"
    },
    "fontWeight": {
      "$value": {
        "$value": 400,
        "$type": "fontWeight"
      },
      "$type": "fontWeights"
    }
  },
  "metric.color": {
    "$value": {
      "$value": {
        "$value": "#002f48",
        "$type": "color",
        "$description": "Midnight — deep headings, secondary brand"
      },
      "$type": "color",
      "$description": "Page headings"
    },
    "$type": "color"
  },
  "metric.typography": {
    "fontSize": {
      "$value": {
        "$value": "24px",
        "$type": "fontSizes"
      },
      "$type": "fontSizes"
    },
    "fontWeight": {
      "$value": {
        "$value": 700,
        "$type": "fontWeight"
      },
      "$type": "fontWeights"
    }
  },
  "search.global.text": {
    "$value": {
      "$value": {
        "$value": "#002f48",
        "$type": "color",
        "$description": "Midnight — deep headings, secondary brand"
      },
      "$type": "color",
      "$description": "Page headings"
    },
    "$type": "color"
  },
  "search.inline.text": {
    "$value": {
      "$value": {
        "$value": "#002f48",
        "$type": "color",
        "$description": "Midnight — deep headings, secondary brand"
      },
      "$type": "color",
      "$description": "Page headings"
    },
    "$type": "color"
  },
  "search.within.text": {
    "$value": {
      "$value": {
        "$value": "#002f48",
        "$type": "color",
        "$description": "Midnight — deep headings, secondary brand"
      },
      "$type": "color",
      "$description": "Page headings"
    },
    "$type": "color"
  },
  "search.srp.text": {
    "$value": {
      "$value": {
        "$value": "#002f48",
        "$type": "color",
        "$description": "Midnight — deep headings, secondary brand"
      },
      "$type": "color",
      "$description": "Page headings"
    },
    "$type": "color"
  },
  "select.color.text": {
    "$value": {
      "$value": {
        "$value": "#002f48",
        "$type": "color",
        "$description": "Midnight — deep headings, secondary brand"
      },
      "$type": "color",
      "$description": "Page headings"
    },
    "$type": "color"
  }
} as const;

export type TokenPath  = keyof typeof tokens;
export type TokenValue = typeof tokens[TokenPath];
