import type { Meta, StoryObj } from '@storybook/react';
import React from 'react';
import { VendorBadge } from './vendorBadge';
const meta: Meta<typeof VendorBadge> = { title: 'Components/VendorBadge', component: VendorBadge, parameters: { layout: 'centered' } };
export default meta;
type Story = StoryObj<typeof VendorBadge>;
export const Default: Story = { args: { name: 'GE Healthcare', tier: 'preferred' } };
export const Approved: Story = { args: { name: 'Philips Healthcare', tier: 'approved' } };
export const Standard: Story = { args: { name: 'Medline Industries', tier: 'standard' } };
export const New: Story = { args: { name: 'Sunrise Medical', tier: 'new' } };
export const AllTiers: Story = { parameters: { layout: 'padded' }, render: () => (<div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}><VendorBadge name="GE Healthcare" tier="preferred" /><VendorBadge name="Philips Healthcare" tier="approved" /><VendorBadge name="Medline Industries" tier="standard" /><VendorBadge name="Sunrise Medical" tier="new" /></div>) };
